ALTER TABLE public.retailer_external_unsorted
DROP CONSTRAINT retailer_external_unsorted_pkey;

ALTER TABLE public.retailer_external_unsorted
ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;